### PR TITLE
Fix reference to golden-diff in tests/Makefile

### PR DESCRIPTION
**Pull request by psalaberria002**

### CODE REVIEW

**Review by jjo — APPROVED** [review]
LGTM, thanks for the fix

**Review by jbianquetti-nami — APPROVED** [review]

**Comment by psalaberria002** [comment]
ping

**Comment by psalaberria002** [comment]
Can this get merged please?

**Comment by dbarranco** [comment]
Sorry for the late review. LGTM

**Review by dbarranco — APPROVED** [review]

**Pull request merged**
